### ISSUE TITLE
Next.js SSR has no styles

### ISSUE THREAD

**Issue by proxima-b-alpha** [pankod/superplate#224]
I notice that Next.js with Bootstrap `has not styles rendered in Server Side Render`. But when loaded in browser (CSR) it renders the styles properly.

**Issue:** Looks like on SSR styles are not hydrated.

**Project Info:**

```
√ What will be the name of your app · nextjs-superplate
√ Package manager: · yarn
√ UI framework: · bootstrap
√ CSS Preprocessor: · css
√ Features: ·
√ Hooks ·
√ State Management: · redux
√ i18n - Internationalization · none
√ Linting tools: ·
√ Testing Framework: · testing-library
√ E2E Testing framework: · none
√ Docker integration: · none
√ Continuous integration: · none
```

**package.json**

```
{
  "name": "nextjs-superplate",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "test": "jest -c test/jest.config.js"
  },
  "dependencies": {
    "next": "10.0.3",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "next-compose-plugins": "^2.2.1",
    "bootstrap": "^4.5.3",
    "react-bootstrap": "^1.4.3",
    "react-redux": "^7.2.2",
    "@reduxjs/toolkit": "^1.5.0"
  },
  "devDependencies": {
    "@types/node": "^14.14.13",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "typescript": "^4.1.3",
    "@types/react-redux": "^7.1.16",
    "@testing-library/react": "^11.2.3",
    "@testing-library/react-hooks": "^5.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.3",
    "ts-jest": "^26.4.4",
    "nock": "^13.0.6",
    "isomorphic-unfetch": "^3.1.0",
    "dotenv": "^8.2.0"
  }
}
```

**SSR**
![SSR (2)](https://user-images.githubusercontent.com/4058376/112145135-02374f80-8c00-11eb-8c42-e5959616a18d.png)

**CSR**
![CSR (2)](https://user-images.githubusercontent.com/4058376/112145146-06636d00-8c00-11eb-8879-9b5836af3218.png)

**Comment by omeraplak** [comment]
Hi @proxima-b-alpha ,
Everything looks right, according to [react-bootstrap's documentation](https://react-bootstrap.github.io/getting-started/introduction/). As far as we researched, we could not find a solution. Have you any ideas on how to fix it?

**Comment by proxima-b-alpha** [comment]
> Hi @proxima-b-alpha ,
> Everything looks right, according to [react-bootstrap's documentation](https://react-bootstrap.github.io/getting-started/introduction/). As far as we researched, we could not find a solution. Have you any ideas on how to fix it?

Hi @omeraplak No idea about the fix yet. I'm trying to find a way to hydrate custom and bootstrapp *.css / *.sass files in Next.js to make it work. Next.js has an example of hydrating [Styletron for SSR](https://github.com/vercel/next.js/blob/canary/examples/with-styletron/pages/_document.js) Need to do something similar.

**Comment by omeraplak** [comment]
Hi @proxima-b-alpha ,
I understand. It seemed more correct for us to add this option to the document. We will update the document soon.

**Comment by umucorn** [comment]
Since there is no any official or commonly accepted way of handling this in Next.js (unlike styled-components etc.), we don't consider including a best practice solution for this problem in boilerplate yet. If you have a solution for this problem, you can always open an issue in the future. 

Respectfully closing.
