### ISSUE TITLE
ERROR SAOError

### ISSUE THREAD

**Issue by AlexandreVerhoye** [pankod/superplate#225]
Hi, I tried to create a new project with config below, and I got an error "ERROR SAOError" 

✔ Cloned remote source successfully.
✔ What will be the name of your app · testSuperplate
✔ Package manager: · npm
✔ UI framework: · antd
✔ CSS Preprocessor: · css
✔ Features: · fetch,storybook,svgr,env,reverse-proxy
✔ Hooks · swr,react-use
✔ State Management: · redux
✔ i18n - Internationalization · next-translate
✔ Linting tools: · prettier
✔ Testing Framework: · enzyme
✔ E2E Testing framework: · webdriverio
✔ Docker integration: · Docker
✔ Continuous integration: · github-actions
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/pirate/testSuperplate
    at ChildProcess.<anonymous> (/home/pirate/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  sao: true
}

**Comment by omeraplak** [comment]
@AlexandreVerhoye Hi,
I think it is related to the fetch plugin. We fixed the error. Could you try again?

I created a project with the same plugins,
````
✔ Cloned remote source successfully.
✔ What will be the name of your app · testSuperplate
✔ Package manager: · npm
✔ UI framework: · antd
✔ CSS Preprocessor: · css
✔ Features: · fetch,storybook,svgr,env,reverse-proxy
✔ Hooks · swr,react-use
✔ State Management: · redux
✔ i18n - Internationalization · next-translate
✔ Linting tools: · prettier
✔ Testing Framework: · enzyme
✔ E2E Testing framework: · webdriverio
✔ Docker integration: · Docker
✔ Continuous integration: · github-actions

Success! Created superplateTest at /Users/omer/Projects/testSuperplate

````

**Comment by AlexandreVerhoye** [comment]
Hey, I tried again, I still has the same issue :

✔ Cloned remote source successfully.
✔ What will be the name of your app · testSp
✔ Package manager: · npm
✔ UI framework: · antd
✔ CSS Preprocessor: · css
✔ Features: · fetch,storybook,svgr,env,reverse-proxy
✔ Hooks · swr,react-query,react-use
✔ State Management: · redux
✔ i18n - Internationalization · next-translate
✔ Linting tools: · eslint,prettier
✔ Do you want to use lint-staged? · lint-staged
✔ Testing Framework: · jest
✔ E2E Testing framework: · none
✔ Docker integration: · Docker
✔ Continuous integration: · none
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/pirate/testSp
    at ChildProcess.<anonymous> (/home/pirate/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:369:20)
    at maybeClose (node:internal/child_process:1067:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  sao: true
}

I did the same initial command : npx superplate-cli testSp

**Comment by omeraplak** [comment]
@AlexandreVerhoye Hi,
Could you share node and npm versions?
````
npm -v
node -v
````

**Comment by AlexandreVerhoye** [comment]
Hi @omeraplak , here is my Node and NPM version :

alex@rpi:~$ npm -v
7.7.4
alex@rpi:~$ node -v
v15.12.0

**Comment by omeraplak** [comment]
Hi @AlexandreVerhoye ,
Is it possible to use node 14? It seems that many packages do not support node 15. We will work on it but I have no date for when we can do it.

**Comment by AlexandreVerhoye** [comment]
Hey @omeraplak no problem, thanks for the help, and thanks for SuperPlate, it's really helpful ! 👌🏻
