### ISSUE TITLE
Upgrade to latest nextjs version.

### ISSUE THREAD

**Issue by RocktimSaikia** [pankod/superplate#227]
I am currently using `superplate` to scaffold my personal projects. But the Next.js version is not up to date. Recently [Next.js released `v10.1` ](https://nextjs.org/blog/next-10-1) which is very optimized in many ways. It would be nice if you upgrade it to the latest version as well. Also, this is not a major release so there should be no issue with upgrading IMO.

**Comment by omeraplak** [comment]
@RocktimSaikia Hi,
We will do the upgrade today. We will inform you soon!

**Comment by omeraplak** [comment]
@RocktimSaikia Hi,
We've upgraded next.js version to 10.1.2 and released 1.0.7.
