### ISSUE TITLE
TailwindCSS styles don't work in Storybook

### ISSUE THREAD

**Issue by r0zar** [pankod/superplate#231]
I've noticed on a few projects there is some post-generation config work required to get TailwindCSS styles to work in Storybook.

So far I've just created a [created a base styles.js file](https://tailwindcss.com/docs/adding-base-styles#using-css) and imported it in to `.storybook/preview.js` to get the styles in place.

This feels sub-optimal, as the main app seems to work without the base styles file- I'm just not certain how it's wired up in superplate.

Thanks!

**Comment by wzulfikar** [comment]
In main app, it works because superplate import it in pages/_app.tsx. Example:

![image](https://user-images.githubusercontent.com/7823011/114900294-51128680-9e46-11eb-9e49-26c710d4d6f9.png)

**Comment by wzulfikar** [comment]
So, i think, you can change line 3 to your own css file. For example, if you have this file:

```css
/* File: src/styles/global.css */

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  h1 {
    @apply text-2xl;
  }
  h2 {
    @apply text-xl;
  }
}
```

you can replace `import "tailwindcss/tailwind.css"` with `import "@styles/global.css"` and it should work.

**Comment by r0zar** [comment]
This makes sense to me. Thank you @wzulfikar

**Comment by r0zar** [comment]
Ill close this and re-open it in the core plugins repo.
