### ISSUE TITLE
404 Not Found - GET https://registry.npmjs.org/superplate-clinpx - Not found

### ISSUE THREAD

**Issue by ryadav96** [pankod/superplate#232]
While running `npx superplate-clinpx my-website`. I am getting  error(- GET https://registry.npmjs.org/superplate-clinpx - Not found).

E:\nextJS>npx superplate-clinpx my-website
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/superplate-clinpx - Not found
npm ERR! 404
npm ERR! 404  'superplate-clinpx@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USER\AppData\Local\npm-cache\_logs\2021-04-21T13_59_44_460Z-debug.log

**Comment by omeraplak** [comment]
@ryadav96 Hi,
It looks like you did a typo. You can run the command directly,`npx superplate-cli my-website`

**Comment by ryadav96** [comment]
Thanks, @omeraplak .
