### ISSUE TITLE
Issue with multiple extend.js wrappers

### ISSUE THREAD

**Issue by MarleyDabb** [pankod/superplate#252]
Hi when using the extend.js wrapper is there a way to make a specific plugin have priority to wrap last?

I'm using nextauth provider as a wrapper but it is being put inside my Layout wrapper from the tailwind plugin which is causing issues. Let me know if there's a solution, thanks.

**Comment by omeraplak** [comment]
Hi @MarleyDabb ,
Unfortunately, there is no plugin priority feature. SAO actions are run in the order of prompts.
