### ISSUE TITLE
Undo Choice

### ISSUE THREAD

**Issue by VelterZI** [pankod/superplate#253]
This isn't an Issue, but here we are.
Superplate is really useful, but whenever I want to start a new project and I accidentally click the wrong choice, I have to redo all of the steps and wait for the packages to be reinstalled. and My internet doesn't have the best speed in the world so It would be nice to have a feature to go back a step and choose a different option.
Maybe there is a feature like that already and I don't know it yet. so If there is, please tell me.
thanks!

**Comment by omeraplak** [comment]
Hi @VelterZI ,
That would be great, but there is no easy way for us to do this. superplate uses "[enquirer](https://github.com/enquirer/enquirer)", this support needs to be added by "[enquirer](https://github.com/enquirer/enquirer)".
