### ISSUE TITLE
Tutorial for example projects after generation codes

### ISSUE THREAD

**Issue by dwebfan** [pankod/superplate#255]
Thanks for making the super useful tools!

The animation image on CLI usage is pretty clear. I'm thinking one tutorial may be helpful to show people how to add new pages and make one simple website after generation. :-)

**Comment by omeraplak** [comment]
Hello @dwebfan ,
I don't fully understand your need. Could you give some more details?

**Comment by dwebfan** [comment]
Thanks for reply.

Next.js has a tutorial paper https://nextjs.org/learn/basics/create-nextjs-app. If one document can teach beginner how to integrate the tutorial with the bootstrap project, it would be very useful.
