### ISSUE TITLE
Ability to add plugins after initialising an app

### ISSUE THREAD

**Issue by MarleyDabb** [pankod/superplate#256]
Will there be a feature in the future that allows for plugins to be added after an application has been initialised. So for example, after I have my app already running with some selected plugins, I can run the superplate-cli command to add in other plugins that I may not have needed the first time I created my superplate?

**Comment by omeraplak** [comment]
Hi @MarleyDabb,
The way to do this is to follow the documentation. For example, if you want to add Chakra UI, you should just follow this document [Chakra UI](https://pankod.github.io/superplate/docs/nextjs/chakra-ui).
