### ISSUE TITLE
superplate-cli has encountered an error

### ISSUE THREAD

**Issue by adreszer** [pankod/superplate#258]
Hey Guys,
There is an error when you try to create a project with antd. 

**Command:** npx superplate-cli test_superplate
npx: installed 138 in 4.619s
√ Select your project type » Next.js
√ Cloned remote source successfully.
√ What will be the name of your app · test_superplate
√ Package manager: · yarn
√ UI framework: · antd
√ CSS Preprocessor: · scss
√ Features: · axios,env
√ Hooks · react-query
√ State Management: · none
√ i18n - Internationalization · next-translate
√ Linting tools: ·
√ Testing Framework: · none
√ E2E Testing framework: · none
√ Docker integration: · Docker
√ Continuous integration: · none
error An unexpected error occurred: "https://registry.yarnpkg.com/antd/-/antd-4.16.4.tgz: Request failed \"404 Not Found
\"".

superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in E:\Programowanie\23.06\test_superplate
    at ChildProcess.<anonymous> (C:\Users\XXX\AppData\Roaming\npm-cache\_npx\19160\node_modules\superplate-cli\node_modules\sao\dist\chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\XXX\AppData\Roaming\npm-cache\_npx\19160\node_modules\superplate-cli\node_modules\sao\dist\chunk.T-GsVNZ1.js:460:27)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  sao: true
}

Thanks a lot for your work!

**Comment by adreszer** [comment]
By the way you can work around that by removing Antd from package.json and installing manually the latest version, which I think they downgraded, hence the error.

**Comment by omeraplak** [comment]
Hi @adreszer ,
I cannot reproduce. If the problem persists, can you reopen the issue?
