### ISSUE TITLE
cli encountered an error

### ISSUE THREAD

**Issue by surajkrishan** [pankod/superplate#260]
Hi I got this error after generating the project PFB screenshot for reference, i am using node v14

![image](https://user-images.githubusercontent.com/32816421/125192591-4198b300-e266-11eb-9a3d-c77d5bb78a8f.png)

**Comment by lordwill000** [comment]
Same for me

**Comment by omeraplak** [comment]
Hi @lordwill000 @surajkrishan ,
Thank you for contacting us. We've fixed your issue and release 1.2.1. Could you try again?
