### ISSUE TITLE
Feature Request - Custom Server Option for Nextjs

### ISSUE THREAD

**Issue by gjsjy** [pankod/superplate#272]
Hi Pankod,

Is it possible to enable a custom server option with this fantastic superplate? If I have to run the nextjs with express server. What would be the package and config has to be updated?

any help..

Thanks,

GJ

**Comment by omeraplak** [comment]
Hi @gjsjy ,
Nextjs + express setup is a anti-pattern.

You can checkout official documentation;
https://nextjs.org/docs/advanced-features/custom-server
