### ISSUE TITLE
Not downloads anything or creates folder

### ISSUE THREAD

**Issue by ay0ks** [pankod/superplate#276]
Hello, when I try to execute `npx superplate-cli pastebin`, I answer the questions but it not downloads anything

![IMG_20210825_172816](https://user-images.githubusercontent.com/43708417/130819663-abdc61df-e4f6-4eeb-8a46-50507ec194e4.jpg)

**Comment by omeraplak** [comment]
Hey @ay0ks ,
If this problem persists, can you open it again?
