### ISSUE TITLE
Licence of the created project

### ISSUE THREAD

**Issue by gavento** [pankod/superplate#280]
_What is the license of a project created by superplate?_

MIT is stated in the _generated_ readme but I wonder if that is just a suggestion/default for the new project, or whether that is the license you (superplate) are requiring the project to have. (I understand that the superplate code itself is MIT licensed but I am not clear on what this impies)
For example: I may want to create projects using CC-BY-NC or GPL and I am wondering if superplate is an option.
A clarification on that in the documentation or readme would be very welcome!

Thanks for the awesome templating tool!

**Comment by omeraplak** [comment]
@gavento Hi,
Thank you for your attention! superplate is licensed by MIT. For projects created with Superplate, the MIT license is default only. If you'd like to send a PR explaining this, we'll happily merge!
