### ISSUE TITLE
build failure (react)

### ISSUE THREAD

**Issue by Emyboy** [pankod/superplate#289]
Immediately after creating a project using superplate, I ran the build command `npm run build` 

and I get the error below 

![image](https://user-images.githubusercontent.com/34845973/138372206-b7ba3360-0aab-448c-afe7-9f361a76a376.png)

I followed all the instructions, but still couldn't get it to build 😞

**Comment by Emyboy** [comment]
Getting same error, I'm not able to work with the react boilerplate at all 😔😔

**Comment by omeraplak** [comment]
Hey,
This should solve your problem, [https://stackoverflow.com/a/60947470](https://stackoverflow.com/a/60947470)
