### ISSUE TITLE
How to create a superplate scaffolding without Typescript

### ISSUE THREAD

**Issue by Yael95** [pankod/superplate#290]
Every option seems to add Typescript to the project, is there an option for the scaffolding excluding typescript.

**Comment by luisjuniorj** [comment]
> Every option seems to add Typescript to the project, is there an option for the scaffolding excluding typescript.

Yes, that would be nice

**Comment by omeraplak** [comment]
It's not in our plans for now, but we'd love to support it if the Community creates it.
