### ISSUE TITLE
yarn dev runs for 2-3 minutes then browser page throws a TypeError, how do I fix?  

### ISSUE THREAD

**Issue by SPRIME01** [pankod/superplate#296]
The following is the error message I get. I didn't do anything but install using the superplate cli : 

Server Error

TypeError: Cannot read property 'push' of null

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
useHistory
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/@pankod/refine-nextjs-router/dist/refine-nextjs-router.cjs.development.js (44:25)
NextRouteComponent
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/@pankod/refine-nextjs-router/dist/refine-nextjs-router.cjs.development.js (134:21)
processChild
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/react-dom/cjs/react-dom-server.node.development.js (3353:14)
resolve
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/react-dom/cjs/react-dom-server.node.development.js (3270:5)
ReactDOMServerRenderer.render
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/react-dom/cjs/react-dom-server.node.development.js (3753:22)
ReactDOMServerRenderer.read
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/react-dom/cjs/react-dom-server.node.development.js (3690:29)
Object.renderToString
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/react-dom/cjs/react-dom-server.node.development.js (4298:27)
Object.renderPage
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/next/dist/server/render.js (686:46)
Object.defaultGetInitialProps
file:///mnt/c/Users/sprim/Focus%20Areas/Projects/Dev/iAttentionRefine/node_modules/next/dist/server/render.js (316:51)
Function.getInitialProps
node_modules/next/dist/pages/_document.js (145:19)

**Comment by Nathan-G1** [comment]
The same thing happening here. The server starts and then fails when opening http://localhost:3000 on the browser.

```
wait  - compiling /[resource] (client and server)
event - compiled client and server successfully in 883 ms (3346 modules)
error - TypeError: Cannot read property 'push' of null
```

**Comment by SPRIME01** [comment]
If you don't select the option to generate a sample page it will work.
