### ISSUE TITLE
'yarn dev' gives error with superplate 

### ISSUE THREAD

**Issue by praveen0311** [pankod/superplate#297]
yarn run v1.22.15
warning ..\..\..\package.json: No license field
$ craco start
(node:8940) UnhandledPromiseRejectionWarning: Error: Can't find file-loader in the developmen
t webpack config!

This error probably occurred because you updated react-scripts or craco. Please try updating
craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

If that doesn't work, craco-less needs to be fixed to support the latest version.
Please check to see if there's already an issue in the DocSpring/craco-less repo:

   * https://github.com/DocSpring/craco-less/issues?q=is%3Aissue+webpack+file-loader

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue+webpack+file-loader
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue+webpack+file-loader

**Comment by gino8080** [comment]
same error

**Comment by omeraplak** [comment]
Hey,
We've updated `craco-less` to v2. Could you try again?

**Comment by gino8080** [comment]
> Hey, We've updated `craco-less` to v2. Could you try again?

yes i can confirm it's working with craco v2
jusg got an error with ```Failed to parse source map from ../superplate/node_modules/export-to-csv/build/export-to-csv.js.map'```
but the project builds and works! 
thanks!

**Comment by omeraplak** [comment]
> > Hey, We've updated `craco-less` to v2. Could you try again?
> 
> yes i can confirm it's working with craco v2 jusg got an error with `Failed to parse source map from ../superplate/node_modules/export-to-csv/build/export-to-csv.js.map'` but the project builds and works! thanks!

Many thanks for the quick response! Let's go!

Other error is related to CRA@5 :(
