### ISSUE TITLE
react-scripts dependency conflict with @craco/craco package

### ISSUE THREAD

**Issue by Raepheles** [pankod/superplate#303]
CLI options:
**Project type**: React
**UI Framework**: Tailwind
**CSS Preprocessor**: Scss
**Features**: fetch, storybook, env, reverse-proxy
**Hooks**: react-query
**State Management**: redux
**rtk query**: none
**i18n**: react-i18next
**linting tools**: eslint
**testing framework**: jest
**e2e testing framework**: none
**docker integration**: Docker
**Continuous integration**: github-actions

Although they are not relevant (as far as I see) these are the settings I've chosen. CLI gives error while installing dependencies which only shows child_process stack trace. When I go to created project folder and run `npm i` myself I see the problem is with `@craco/craco` package. This package has internal dependency to `react-scripts` version 4 as you can [see here](https://github.com/gsoft-inc/craco/blob/master/packages/craco/package.json). superplate cli on the other hand installs `react-scripts` version 5 which creates a conflict.

Posible solution would be to install `react-scripts` v4 until craco's developers start supporting v5 on main branch (they already have a branch for v5 [here](https://github.com/gsoft-inc/craco/tree/support-cra5))

**Comment by omeraplak** [comment]
Hey,
We've fixed this issue!
