### ISSUE TITLE
Type Error on Project Build

### ISSUE THREAD

**Issue by burhanahmed92** [pankod/superplate#306]
Its showing me this error after i run build command on fresh setup

Type error: 'Component' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<{}, any, any> | null' is not a valid JSX element.
    Type 'Component<{}, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<{}, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/Users/apple/Desktop/SoftwareAlliance/React/example/superplate/node_modules/react-bootstrap/node_modules/@types/react/index").ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'.

**Comment by nur8sultan** [comment]
@omeraplak hey! having same issue 
node v18.7.0
yarn v1.22.19

**Comment by omeraplak** [comment]
Hey @nur8sultan ,
we fixed this bug. Thanks a lot for your help! 💥
