### ISSUE TITLE
ERROR SAOError: Failed to install packages

### ISSUE THREAD

**Issue by supercoolx** [pankod/superplate#311]
I typed command `npx superplate-cli app`.
And I configured like this:
```
√ Cloned remote source successfully.
√ Select your project type » react
√ What will be the name of your app · app
√ Package manager: · npm
√ UI framework: · tailwind
√ CSS Preprocessor: · css
√ Features: · axios
√ Hooks ·
√ State Management: · redux
√ Do you want to use RTK Query ? · none
√ i18n - Internationalization · none
√ Linting tools: · eslint
√ Testing Framework: · jest
√ E2E Testing framework: · none
√ Docker integration: · none
√ Continuous integration: · none
√ Would you like to share your choices with us anonymously? · no
```

But it shows following error:
```
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in D:\studio\GitHub\app
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\npm-cache\_npx\68a94a7f4a156bcd\node_modules\sao\dist\chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (C:\Users\Administrator\AppData\Local\npm-cache\_npx\68a94a7f4a156bcd\node_modules\sao\dist\chunk.T-GsVNZ1.js:460:27)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  sao: true
}
```

My node and npm version:
```
npm --version
8.6.0
node --version
v16.11.0
```

**Comment by aenawi** [comment]
Hi

Same error here using `npx superplate-cli testing-01`:

```
✔ Cloned remote source successfully.
✔ Package manager: › pNpm
✔ Select your project type › nextjs
✔ What will be the name of your app · testing-01
✔ UI framework: · none
✔ CSS Preprocessor: · css
✔ Features: · storybook,svgr,env,reverse-proxy,bundle-analyzer,apollo-graphql,graphql-request
✔ Hooks ·
✔ State Management: · none
✔ i18n - Internationalization · next-i18next
✔ Linting tools: ·
✔ Testing Framework: · jest
✔ E2E Testing framework: · none
✔ Docker integration: · none
✔ Continuous integration: · none
✔ Would you like to share your choices with us anonymously? › No
```

Error message:
```
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /workspace/superplate/testing-01
    at ChildProcess.<anonymous> (/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}
```

I'm using the following node and pnpm versions:
```
node --version
v16.15.0
pnpm --version
7.9.0
```

**Comment by BosioGerman** [comment]
Hi, same here

`✔ Cloned remote source successfully.
✔ Package manager: › pNpm
✔ Select your project type › refine-nextjs
✔ What will be the name of your app · carrito
✔ Do you want to use a UI Framework?: · antd
✔ Do you want a customized theme?: · antd-css
✔ Data Provider: · data-provider-custom-json-rest
✔ Auth Provider: · auth-provider-custom
✔ Do you want to add example pages? · antd-example-pages
✔ Do you want a customized layout? · antd-custom-layout
✔ Do you want to add Kbar command pallette: · kbar
✔ i18n - Internationalization: · i18n-antd
✔ Would you like to share your choices with us anonymously? › I want to share anonymously! Thank you! ❤️
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/german/source/learning/carrito/carrito
    at ChildProcess.<anonymous> (/home/german/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  sao: true
}
`
`
node --version
v16.11.1
pnpm --version
7.9.5
`

**Comment by omeraplak** [comment]
Hey @aenawi @BosioGerman @supercoolx 👋,
Thank you for contacting us! 
I could not reproduce the error 🛹 If the project folder was created successfully, can you try to go to that folder and run `npm i` or `pnpm i`? Maybe so we can see the error in more detail 🚀

My versions:
node: v16.14.0
pnpm: 6.11.0
npm: 8.3.1

**Comment by kbarcelo** [comment]
Im having this issue as well. Any luck?

**Comment by coffin5257** [comment]
Try to use the official NPM Registry (https://registry.npmjs.org/)

**Comment by omeraplak** [comment]
Hey,
We've fixed this issue 👊

**Comment by ceilitellu777** [comment]
i still get the same error
