### ISSUE TITLE
Not able to generate CRA project

### ISSUE THREAD

**Issue by amal-chandran** [pankod/superplate#321]
![image](https://user-images.githubusercontent.com/29562232/209480524-d370535b-bd62-4745-92e7-7c0b07b85383.png)

**Comment by aliemir** [comment]
Hey @amal-chandran, sorry for the issue ☹️ We had a minor change in one of the files we create when you select `Custom Layout` for `Ant Design` and that change had a small typo and broke the template. Just sent a fix and now it should be fine 🚀 🚀
