### ISSUE TITLE
ERROR ReferenceError: ejs:51

### ISSUE THREAD

**Issue by ha-family** [pankod/superplate#337]
node version v16.19.1

![image](https://user-images.githubusercontent.com/8111587/229336588-8fe06431-25a5-43bb-974a-565543aa7528.png)

**Comment by aliemir** [comment]
Hey @ha-family sorry for the issue. Can you share the command you’ve used to run superplate?

**Comment by ha-family** [comment]
sure

`npx superplate-cli my-project`

then i try to set version number, it works.

`npx superplate-cli@1.15.1 my-project`
