### ISSUE TITLE
Bad format of package.json commands

### ISSUE THREAD

**Issue by tomaszs** [pankod/superplate#341]
Package.json of the generated project contains such commands:

```
    "lint": "eslint '**/*.{js,jsx,ts,tsx}'",
    "prettier": "prettier --write '**/*.{js,jsx,ts,tsx}'",
```

These won't work at least on Windows / Bash. 

To fix it you'd have to remove single quotes:

```
    "lint": "eslint **/*.{js,jsx,ts,tsx}",
    "prettier": "prettier --write **/*.{js,jsx,ts,tsx}",
```

In both commands

**Comment by BatuhanW** [comment]
Hello @tomaszs Feel free to create a PR.

**Comment by shivam-sharma7** [comment]
@BatuhanW close this now, no need
